name: bump-casks
on:
  workflow_dispatch:                      # allow manual trigger
  push:
    tags:
      - '*'
  schedule:
    # Time is UTC, so below is running everyday at 8AM and 8PM PST
    - cron:  '0 4,16 * * *'

jobs:
  bump-casks:
    runs-on: macos-latest
    steps:
        - name: Bump Homebrew Cask
          uses: IssacL891/action-homebrew-bump-cask@master
          with:
            token: ${{ secrets.BUMP_CASK_TOKEN }}
            tap:   issacl891/brewery
            cask: mangayomi, yaagl-gi-os, yaagl-gi, yaagl-hsr-os, yaagl-hsr, yaagl-zzz-os, yaagl-zzz, anymex, dartotsu
            livecheck: true